import argparse
import json
import math
import os
import subprocess
from pathlib import Path


def parse_args():
    parser = argparse.ArgumentParser(
        description="Find and optionally cut in-play tennis segments from a tracking JSONL log."
    )
    parser.add_argument("--jsonl", required=True, help="Tracking JSONL generated by track_ball_yolo.py.")
    parser.add_argument("--video", required=True, help="Source video to cut.")
    parser.add_argument("--output-dir", required=True, help="Directory for the manifest and optional clips.")
    parser.add_argument("--fps", type=float, default=30.0, help="Video frame rate used for frame/time conversion.")
    parser.add_argument(
        "--max-event-gap-frames",
        type=int,
        default=210,
        help="Maximum gap between bounce events that still belongs to the same in-play segment.",
    )
    parser.add_argument(
        "--min-events",
        type=int,
        default=2,
        help="Minimum bounce events required for a segment unless --keep-single-event-segments is set.",
    )
    parser.add_argument(
        "--keep-single-event-segments",
        action="store_true",
        help="Keep one-bounce segments, useful for aces, faults, or very short points.",
    )
    parser.add_argument("--pre-roll-frames", type=int, default=90, help="Frames to include before first event.")
    parser.add_argument("--post-roll-frames", type=int, default=30, help="Fallback frames to include after last event.")
    parser.add_argument(
        "--dynamic-end",
        action="store_true",
        default=True,
        help="Infer segment ends from the selected ball trail after the last event.",
    )
    parser.add_argument(
        "--fixed-end",
        action="store_false",
        dest="dynamic_end",
        help="Use fixed post-roll only; disables dynamic selected-ball ending.",
    )
    parser.add_argument(
        "--end-scan-frames",
        type=int,
        default=120,
        help="Maximum frames after the last event to scan for active ball continuation.",
    )
    parser.add_argument(
        "--end-dead-gap-frames",
        type=int,
        default=7,
        help="End a point when selected ball frames disappear for at least this many frames.",
    )
    parser.add_argument(
        "--end-jump-px",
        type=float,
        default=150.0,
        help="End a point before an implausible selected-ball jump after the last event.",
    )
    parser.add_argument(
        "--end-margin-frames",
        type=int,
        default=3,
        help="Frames to keep after the last plausible selected-ball frame.",
    )
    parser.add_argument(
        "--merge-gap-frames",
        type=int,
        default=45,
        help="Merge final segments separated by this many frames or fewer.",
    )
    parser.add_argument(
        "--attach-single-event-gap-frames",
        type=int,
        default=300,
        help="Attach a one-event group to the previous segment when it is within this many frames.",
    )
    parser.add_argument(
        "--write-clips",
        action="store_true",
        help="Write one video clip per detected segment with ffmpeg.",
    )
    parser.add_argument(
        "--concat-output",
        help="Optional output video path for a single concatenated in-play video. Requires --write-clips.",
    )
    parser.add_argument(
        "--reencode",
        action="store_true",
        help="Re-encode clips instead of stream-copying. Slower, but more accurate around cut points.",
    )
    return parser.parse_args()


def read_tracking_log(path):
    events = []
    ball_frames = []
    total_frames = 0
    with open(path, "r", encoding="utf-8") as handle:
        for line in handle:
            if not line.strip():
                continue
            row = json.loads(line)
            total_frames = max(total_frames, int(row["frame"]))
            ball = row.get("ball")
            if ball is not None:
                ball_frames.append(
                    {
                        "frame": int(row["frame"]),
                        "center": ball.get("center"),
                        "track_id": ball.get("track_id"),
                        "interpolated": bool(ball.get("interpolated")),
                    }
                )
            event = row.get("event")
            if event is not None:
                events.append(
                    {
                        "log_frame": int(row["frame"]),
                        "event_frame": int(event["frame"]),
                        "side": event.get("side"),
                        "pattern": event.get("pattern"),
                        "point": event.get("point"),
                        "world_point": event.get("world_point"),
                    }
                )
    return events, ball_frames, total_frames


def group_events(events, max_gap_frames):
    if not events:
        return []
    ordered = sorted(events, key=lambda event: event["event_frame"])
    groups = [[ordered[0]]]
    for event in ordered[1:]:
        prev = groups[-1][-1]
        if event["event_frame"] - prev["event_frame"] <= max_gap_frames:
            groups[-1].append(event)
        else:
            groups.append([event])
    return groups


def attach_single_event_tails(groups, max_gap_frames):
    attached = []
    for group in groups:
        if len(group) == 1 and attached:
            previous = attached[-1]
            if group[0]["event_frame"] - previous[-1]["event_frame"] <= max_gap_frames:
                previous.extend(group)
                continue
        attached.append(group)
    return attached


def infer_segment_end(group, ball_frames, total_frames, args):
    last_event_frame = group[-1]["event_frame"]
    fallback_end = min(total_frames, last_event_frame + args.post_roll_frames)
    if not args.dynamic_end:
        return fallback_end

    scan_end = min(total_frames, last_event_frame + max(args.post_roll_frames, args.end_scan_frames))
    selected = [
        frame
        for frame in ball_frames
        if last_event_frame <= frame["frame"] <= scan_end and frame.get("center") is not None
    ]
    if not selected:
        return fallback_end

    last_plausible = last_event_frame
    prev = selected[0]
    if not prev.get("interpolated"):
        last_plausible = prev["frame"]

    for current in selected[1:]:
        frame_gap = current["frame"] - prev["frame"]
        if frame_gap >= args.end_dead_gap_frames:
            break

        # Selected-ball track IDs can switch at contact, near the player, or near
        # court lines. Treat large jumps as handoffs and keep scanning until the
        # selected ball actually disappears for a sustained gap.
        if not current.get("interpolated"):
            last_plausible = current["frame"]
        prev = current

    return min(total_frames, max(last_event_frame + 1, last_plausible + args.end_margin_frames))


def merge_segments(segments, merge_gap_frames):
    if not segments:
        return []
    ordered = sorted(segments, key=lambda segment: segment["start_frame"])
    merged = [ordered[0]]
    for segment in ordered[1:]:
        prev = merged[-1]
        if segment["start_frame"] - prev["end_frame"] <= merge_gap_frames:
            prev["end_frame"] = max(prev["end_frame"], segment["end_frame"])
            prev["events"].extend(segment["events"])
            prev["event_count"] = len(prev["events"])
            prev["sides"] = sorted({event.get("side") for event in prev["events"] if event.get("side")})
            prev["patterns"] = sorted({event.get("pattern") for event in prev["events"] if event.get("pattern")})
        else:
            merged.append(segment)
    return merged


def build_segments(events, ball_frames, total_frames, args):
    segments = []
    groups = group_events(events, args.max_event_gap_frames)
    groups = attach_single_event_tails(groups, args.attach_single_event_gap_frames)
    for group in groups:
        if len(group) < args.min_events and not args.keep_single_event_segments:
            continue
        start_frame = max(1, group[0]["event_frame"] - args.pre_roll_frames)
        end_frame = infer_segment_end(group, ball_frames, total_frames, args)
        segments.append(
            {
                "start_frame": start_frame,
                "end_frame": end_frame,
                "event_count": len(group),
                "sides": sorted({event.get("side") for event in group if event.get("side")}),
                "patterns": sorted({event.get("pattern") for event in group if event.get("pattern")}),
                "events": group,
            }
        )
    return merge_segments(segments, args.merge_gap_frames)


def annotate_times(segments, fps):
    for index, segment in enumerate(segments, start=1):
        segment["index"] = index
        segment["start_time"] = frame_to_seconds(segment["start_frame"], fps)
        segment["end_time"] = frame_to_seconds(segment["end_frame"], fps)
        segment["duration"] = max(0.0, segment["end_time"] - segment["start_time"])
    return segments


def frame_to_seconds(frame, fps):
    return max(0.0, (frame - 1) / fps)


def seconds_to_timestamp(seconds):
    millis = int(round((seconds - math.floor(seconds)) * 1000))
    whole = int(math.floor(seconds))
    hours, rem = divmod(whole, 3600)
    minutes, secs = divmod(rem, 60)
    return f"{hours:02d}:{minutes:02d}:{secs:02d}.{millis:03d}"


def write_manifest(path, video, jsonl, fps, total_frames, segments):
    payload = {
        "video": str(video),
        "jsonl": str(jsonl),
        "fps": fps,
        "total_frames": total_frames,
        "segments": segments,
    }
    with open(path, "w", encoding="utf-8") as handle:
        json.dump(payload, handle, indent=2)
        handle.write("\n")


def run_ffmpeg(command):
    subprocess.run(command, check=True)


def write_clips(video, output_dir, segments, reencode):
    clip_paths = []
    for segment in segments:
        clip_path = output_dir / f"segment_{segment['index']:02d}.avi"
        command = [
            "ffmpeg",
            "-y",
            "-ss",
            seconds_to_timestamp(segment["start_time"]),
            "-to",
            seconds_to_timestamp(segment["end_time"]),
            "-i",
            str(video),
        ]
        if reencode:
            command.extend(["-c:v", "mjpeg", "-q:v", "5", "-an"])
        else:
            command.extend(["-c", "copy"])
        command.append(str(clip_path))
        run_ffmpeg(command)
        clip_paths.append(clip_path)
    return clip_paths


def write_concat_video(clip_paths, concat_output):
    concat_list = Path(concat_output).with_suffix(".concat.txt")
    with open(concat_list, "w", encoding="utf-8") as handle:
        for clip_path in clip_paths:
            escaped = str(Path(clip_path).resolve()).replace(chr(39), chr(39) + chr(92) + chr(39) + chr(39))
            handle.write(f"file '{escaped}'\n")
    run_ffmpeg(["ffmpeg", "-y", "-f", "concat", "-safe", "0", "-i", str(concat_list), "-c", "copy", concat_output])


def main():
    args = parse_args()
    jsonl_path = Path(args.jsonl)
    video_path = Path(args.video)
    output_dir = Path(args.output_dir)
    output_dir.mkdir(parents=True, exist_ok=True)

    events, ball_frames, total_frames = read_tracking_log(jsonl_path)
    segments = annotate_times(build_segments(events, ball_frames, total_frames, args), args.fps)
    manifest_path = output_dir / "play_segments.json"
    write_manifest(manifest_path, video_path, jsonl_path, args.fps, total_frames, segments)

    print(f"events: {len(events)}")
    print(f"segments: {len(segments)}")
    print(f"manifest: {manifest_path}")
    for segment in segments:
        print(
            "segment {index:02d}: frames {start_frame}-{end_frame}, "
            "{start}-{end}, {duration:.2f}s, events={event_count}".format(
                index=segment["index"],
                start_frame=segment["start_frame"],
                end_frame=segment["end_frame"],
                start=seconds_to_timestamp(segment["start_time"]),
                end=seconds_to_timestamp(segment["end_time"]),
                duration=segment["duration"],
                event_count=segment["event_count"],
            )
        )

    if args.write_clips:
        clip_paths = write_clips(video_path, output_dir, segments, args.reencode)
        if args.concat_output:
            write_concat_video(clip_paths, args.concat_output)


if __name__ == "__main__":
    main()
